/// <reference lib="webworker" />

import {
  cacheNames,
  isCacheable,
  strategyFor,
} from "@/platform/browser/offline/strategy";

/**
 * The offline shell, and the engine cached beside it
 * (investigation.md 9, Phase 4: "the app handles offline startup … without silent data
 * loss").
 *
 * This is the first piece of Phase 4 and the one with no desktop counterpart:
 * the desktop editor ships an updater and reads TeX Live off a disk, while a
 * browser has a service worker and 22.7 MB of engine to fetch (ADR-011). Once
 * that is in Cache Storage, a second visit compiles with the network switched
 * off, which is the product's claim taken literally.
 *
 * It is written out rather than generated by a toolkit because the policy —
 * what is cached, for how long, and what a deploy replaces — is the part worth
 * reading, and `strategy.ts` holds it as a pure function with its own tests.
 *
 * The host's own headers (`netlify.toml`) mark `/assets/` and `*.wasm`
 * immutable; this cache is authoritative for what it holds, and both agree
 * because both key on names the build changes.
 */

declare const self: ServiceWorkerGlobalScope;

/** Injected at build time: the build's own id, and the engine's version. */
declare const __OPAL_BUILD_ID__: string;
declare const __OPAL_ENGINE_VERSION__: string;

const CACHES = cacheNames(__OPAL_BUILD_ID__, __OPAL_ENGINE_VERSION__);

self.addEventListener("install", () => {
  // Nothing is pre-cached: the engine is 22.7 MB and a person who opens the
  // app to read a document should not pay for it before they compile. What is
  // used is kept; the rest is never fetched.
  void self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      // Every cache but this build's app cache and this engine's cache. A
      // deploy drops the application and keeps the engine.
      const keep = new Set<string>([CACHES.app, CACHES.engine]);
      for (const name of await caches.keys()) {
        if (name.startsWith("opal-") && !keep.has(name)) {
          await caches.delete(name);
        }
      }
      await self.clients.claim();
    })(),
  );
});

async function cacheFirst(request: Request, cache: string): Promise<Response> {
  const store = await caches.open(cache);
  const hit = await store.match(request);
  if (hit) return hit;

  const response = await fetch(request);
  // Cloned before the body is read by the caller: a Response body is a stream
  // and can only be consumed once.
  if (isCacheable(response)) await store.put(request, response.clone());
  return response;
}

async function networkFirst(
  request: Request,
  cache: string,
): Promise<Response> {
  const store = await caches.open(cache);
  try {
    const response = await fetch(request);
    if (isCacheable(response)) await store.put(request, response.clone());
    return response;
  } catch (cause) {
    const hit = await store.match(request);
    if (hit) return hit;
    // A navigation with nothing cached and no network: the shell is what the
    // person asked for, so answer with whichever copy of it exists.
    const shell = await store.match("/");
    if (shell) return shell;
    throw cause;
  }
}

self.addEventListener("fetch", (event) => {
  const request = event.request;
  // Only plain reads of our own origin. A POST is never cached, and another
  // origin's response is not ours to keep.
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  const strategy = strategyFor(url, CACHES);
  if (strategy.kind === "network") return;

  event.respondWith(
    strategy.kind === "cache-first"
      ? cacheFirst(request, strategy.cache)
      : networkFirst(request, strategy.cache),
  );
});
